### PR TITLE
first commit change readme

### PR DESCRIPTION
**Pull request by MohamedAmarPro**

### CODE REVIEW

**Review by annemarchasson — COMMENTED** [review]
it's ok

**Comment by alexandre25091991** [comment]
it's ok too

**Review by h-ambre — COMMENTED** [review]
good

**Review by annemarchasson — APPROVED** [review]
ok2

**Review by h-ambre — APPROVED** [review]
very good

**Comment by alexandre25091991** [comment]
approuved

**Comment by AnthonySenechal** [comment]
ok

**Pull request merged**
